FROM python:3.12-slim

WORKDIR /

COPY src/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/deployment ./deployment

EXPOSE 8501

CMD ["streamlit", "run", "deployment/app.py", "--server.port=8501", "--server.address=0.0.0.0"]