FROM python:3.12-slim

WORKDIR /

COPY src/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/deployment ./deployment
COPY src/logs ./logs

EXPOSE 8000

CMD ["uvicorn", "deployment.api:app", "--host", "0.0.0.0", "--port", "8000"]